Name:		texlive-navydocs
Version:	41643
Release:	2
Summary:	Support for Technical Reports by US Navy Organizations
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/navydocs
License:	lppl1.3
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/navydocs.r%{version}.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/navydocs.doc.r%{version}.tar.xz
Source2:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/navydocs.source.r%{version}.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The navydocs package provides an easy means for creating title
pages and the following supplementary material pages used in
technical reports by United States Navy organizations. These
pages are generated by specifying the page content via a set of
commands and then calling a macro to create the page at its
occurence in the document. This package is provided in the hope
that it proves useful to other Navy organizations, with users
contributing macros for their organizations.

%prep
%setup -c -a1 -a2
%autopatch -p1

%build

%install
rm -rf tlpkg
mkdir -p %{buildroot}%{_texmfdistdir}
cp -a * %{buildroot}%{_texmfdistdir}

%files
%doc %{_texmfdistdir}/source/latex/navydocs
%{_texmfdistdir}/tex/latex/navydocs
%doc %{_texmfdistdir}/doc/latex/navydocs

%post -p %{_sbindir}/texlive.post

%postun
[ "$1" -eq 0 ] && %{_sbindir}/texlive.post
